language: bash

services:
- docker

sudo: required

env:
- ACTION=check  TARGET=x86_64
- ACTION=build  TARGET=x86_64

before_install:
- env
- docker images
- docker info
- docker version
- df -h
#- if [ "$ACTION" = "build" -a -n "$TRAVIS_TAG" ]; then sudo apt-get update && sudo apt-get install -y u-boot-tools || true; fi

script:
- if [ "$ACTION" = "check" ]; then cd ${TRAVIS_BUILD_DIR}/Linux && make           travis_check; fi
- if [ "$ACTION" = "check" ]; then cd ${TRAVIS_BUILD_DIR}/Openbsd && make         travis_check; fi
- if [ "$ACTION" = "check" ]; then cd ${TRAVIS_BUILD_DIR}/scw-boot-tools && make  travis_check; fi
- if [ "$ACTION" = "build" ]; then cd ${TRAVIS_BUILD_DIR}/Linux && make           travis_build; fi
- if [ "$ACTION" = "build" ]; then cd ${TRAVIS_BUILD_DIR}/Openbsd && make         travis_build; fi
- if [ "$ACTION" = "build" ]; then cd ${TRAVIS_BUILD_DIR}/scw-boot-tools && make  travis_build; fi
- ls -laR
